/*  $Id: hbwin_ext.ch,v 0.1 2016/03/06 17:04:00 riztan Exp $ */
/*
 * Llamadas externas (windows) para ejecutar desde script.
 * (c)2016 Riztan Gutierrez
 */

 EXTERNAL WIN_PRINTERLIST
 EXTERNAL WIN_PRINTDATARAW
 EXTERNAL WIN_PRINTFILERAW
 EXTERNAL WIN_PRINTERPORTTONAME
 EXTERNAL WIN_PRINTERSTATUS
 EXTERNAL WIN_PRINTEREXISTS 
 EXTERNAL WIN_PRINTERGETDEFAULT
 EXTERNAL WIN_PRINTERSETDEFAULT

 EXTERNAL WIN_GETPRINTERFONTNAME



