
#ifdef _WIN_
EXTERNAL WIN_OLECREATEOBJECT
#endif

EXTERNAL DRAWBARCODE
EXTERNAL TPY_PDFOPEN

EXTERNAL HB_JSONENCODE
EXTERNAL HB_JSONDECODE

#include "hbxlsxwriter_extern.ch"


//-- Instrucciones en fuentes de TPuy
EXTERNAL TSTATUSBAR
